### PR TITLE
removed name_prefix as it is relevant only for controller build

### PR DESCRIPTION
**Pull request by srinitt**

### CODE REVIEW

**Comment by srinitt** [comment]
I did not consider the multiple controller case.

Did get this error message:
---------------------------------------- 
Error: Unsupported argument

  on control.tf line 25, in module "aviatrix-controller-initialize":
  25:   name_prefix         = "terr"

An argument named "name_prefix" is not expected here.
----------------------------------------

**Comment by arvindsree** [comment]
@inc1t3Ful : Could you look into the error

**Comment by arvindsree** [comment]
Seems to be a bug.. @zhiqiangjin is fixing shortly

**Comment by zhiqiangjin** [comment]
Fixed in another pull request:
https://github.com/AviatrixSystems/terraform-modules/pull/66

**Pull request closed without merging**
